### ISSUE TITLE
[Crash] net/minecraft/client/renderer/texture/IIconRegister

### ISSUE THREAD

**Issue by Markezzz** [pomepome/WailaBC-addon#1]
Hey pomepome,

with the WailaAddonBC-1.0.3.1 we cant start the server without this crash:

> Description: Exception in server tick loop
> 
> cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
>   at cpw.mods.fml.common.LoadController.transition(LoadController.java:163)
>   at cpw.mods.fml.common.Loader.initializeMods(Loader.java:744)
>   at cpw.mods.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:97)
>   at cpw.mods.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:325)
>   at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:287)
>   at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:631)
>   at java.lang.Thread.run(Unknown Source)
> Caused by: java.lang.NoClassDefFoundError: net/minecraft/client/renderer/texture/IIconRegister
>   at java.lang.Class.getDeclaredMethods0(Native Method)
>   at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
>   at java.lang.Class.getDeclaredMethod(Unknown Source)
>   at pome.waila.bcaddon.modules.BCIntegrationTableModule.register(BCIntegrationTableModule.java:53)
>   at pome.waila.bcaddon.WailaAddonBC.postInit(WailaAddonBC.java:54)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at cpw.mods.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:532)
>   at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at cpw.mods.fml.common.LoadController.sendEventToModContainer(LoadController.java:212)
>   at cpw.mods.fml.common.LoadController.propogateStateMessage(LoadController.java:190)
>   at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>   at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>   at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>   at java.lang.reflect.Method.invoke(Unknown Source)
>   at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
>   at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
>   at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
>   at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
>   at com.google.common.eventbus.EventBus.post(EventBus.java:275)
>   at cpw.mods.fml.common.LoadController.distributeStateMessage(LoadController.java:119)
>   at cpw.mods.fml.common.Loader.initializeMods(Loader.java:742)
>   ... 5 more
> Caused by: java.lang.ClassNotFoundException: net.minecraft.client.renderer.texture.IIconRegister
>   at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:101)
>   at java.lang.ClassLoader.loadClass(Unknown Source)
>   at java.lang.ClassLoader.loadClass(Unknown Source)
>   ... 36 more

[crash-2016-06-02_10.07.55-server.txt](https://github.com/pomepome/WailaBC-addon/files/295152/crash-2016-06-02_10.07.55-server.txt)

Thanks for your help. :)

**Comment by pomepome** [comment]
Thank you for your report.
I fixed that.
